name: 01-building-blocks

on: 
    push:
        branches:
            - 'release/**'
      

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "hello, world"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: successful step
              run: |
               echo "i will suceed"
               exit 0
            - name: Say Goodbye
              run: echo "Goodbye !"


 