name: 04 - using Actions

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app 
                
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with: 
                node-version: '20.x'
            - name: install Dependencies
              run:  npm ci
            
            - name: run npm test 
              run: npm run test
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app 
        steps:
            - name: npm build 
              run: echo "testing"

              



